data_augmentation:
  brightness: 0.5
  contrast: 0.5
  saturation: 0.5
  hue: 0.0

training:
  batch_size: 54
  data_folder: "data"
  checkpoint_dir: "checkpoints"
  epochs: 32
  eval_save_every: 25
  optimizer:
    period: 50000
    momentum: 0.9
    lmax: 0.05
    lmin: 0.001
    T0: 10
    l2: 1e-4
    gradient_clip: 5.0

validation:
  batch_size: 128
  data_folder: "data"

test:
  batch_size: 128
  data_folder: "data"

model: "mnasnet1_0"